version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
      target: builder
    command: sh -c "cd apps/web && pnpm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/apps/web/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ../../.env