packages:
  - apps/*
  - packages/**
  - tooling/*
  - scripts

catalog:
  '@types/node': ^24.3.0
  hono: ^4.9.6
  lucide-react: ^0.542.0
  next: ^15.5.2
  typescript: ^5.9.2
  vite: ^7.1.4
  vitest: ^3.2.4
  zod: ^4.1.5

catalogs:
  react19:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1
