packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@types/node': ^24.5.0
  hono: ^4.9.7
  lucide-react: ^0.544.0
  next: ^15.5.3
  next-intl: ^4.3.9
  typescript: ^5.9.2
  vite: ^7.1.5
  vitest: ^3.2.4
  zod: ^4.1.8

catalogs:
  react19:
    '@types/react': ^19.1.13
    '@types/react-dom': ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1

publicHoistPattern:
  - '*prettier*'
